# Include sugarcrm specific configuration
- include_vars: "{{ item }}"
  with_items:
    - sugarcrm.yml
    - version.yml
  tags:
    - configuration
    - update

- name: General | Install Application packages
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl

- name: SugarCRM | Ensure MySQL is running
  command: service mysql start
  ignore_errors: yes
  tags:
    - configuration

- name: SugarCRM | Create apache database user
  mysql_user:
    name: "www-data"
    password: ""
    # priv: "{{ sugarcrm_db_name }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

# - name: SugarCRM | Create SugarCRM database
#   mysql_db:
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     db: "{{ sugarcrm_db_name }}"
#     state: present

# - name: SugarCRM | Create SugarCRM database user
#   mysql_user:
#     name: "{{ sugarcrm_db_user }}"
#     password: "{{ sugarcrm_db_password }}"
#     priv: "{{ sugarcrm_db_name }}.*:ALL,GRANT"
#     state: present
#     login_user: root
#     login_password: "{{ mysql_root_password }}"

- name: SugarCRM | Download application from Github
  sudo: false
  git:
    repo: "https://github.com/{{ application_repository }}/sugarcrm.git"
    dest: "{{ sugarcrm_root_path }}"
    version: "{{ application_version }}"
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
    update: yes
    force: yes
  tags:
    - update
    # - configuration
# TO REMOVE

- name: SugarCRM | Current commit hash
  shell: 'git log -n 1 --pretty=format:"%H" > {{ sugarcrm_root_path }}/.git-version'
  args:
    chdir: "{{ sugarcrm_root_path }}"
  tags:
    - update

- name: Git | Ignore files permissions changes
  command: "git config core.filemode false chdir={{ sugarcrm_root_path }}"
  tags:
    - update

# - name: Ansible | Update scripts
#   copy:
#     src: "{{ sugarcrm_root_path }}/deploy/ansible"
#     dest: /etc/
#   tags:
#     - update

- name: SugarCRM | Configure Apache virtual host
  template: 
    src: etc-apache24-confd-sugarcrm-conf
    dest: /etc/apache2/sites-available/sugarcrm.conf
    owner: root
    mode: 755

- name: SugarCRM | Enable Apache virtual host 
  file: src=/etc/apache2/sites-available/sugarcrm.conf dest=/etc/apache2/sites-enabled/sugarcrm.conf state=link

- name: Apache | Restart the Apache service
  service: 
    name: apache2 
    state: restarted

- name: SugarCRM | Set file permissions
  file:
    path: "{{ sugarcrm_root_path }}"
    mode: 0755
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  # tags:
    # - configuration

- name: SugarCRM | Give write permissions to install directories
  file:
    path: "{{ sugarcrm_root_path }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: 0775
    state: directory
    recurse: yes
  with_items:
    - cache
    - custom
    - data
    - modules

- name: SugarCRM | Give write permissions to install files
  file:
    path: "{{ sugarcrm_root_path }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: 0664
  with_items:
    - config.php
    - config_override.php
    - sugarcrm.log

# - name: vTiger | Configuration file config.php
#   template: 
#     src: vtiger-config.inc.php
#     dest: "{{ vtiger_root_path }}/config.inc.php"
#     owner: root
#     mode: 755

# - name: vTiger | Configuration file app_setup.php
#   copy: 
#     src: vtiger-app_setup.php
#     dest: "{{ vtiger_root_path }}/app_setup.php"
#     owner: root
#     mode: 755

# - name: vTiger | Configuration file user_privileges
#   copy: 
#     src: "{{ item }}"
#     dest: "{{ vtiger_root_path }}/user_privileges/{{ item }}"
#     owner: root
#     mode: 755
#   with_items:
#     - sharing_privileges_1.php
#     - user_privileges_1.php

# - name: vTiger | Configuration file maestrano.json
#   template: 
#     src: vtiger-maestrano.json
#     dest: "{{ vtiger_root_path }}/maestrano.json"
#     owner: www-data
#     group: www-data
#     mode: 777
#   tags:
#     - configuration

# - name: vTiger | Setup Application
#   shell: "php {{ vtiger_root_path }}/app_setup.php"
#   args:
#     chdir: "{{ vtiger_root_path }}"

# - name: vTiger | Apply Maestrano patch
#   shell: "mysql {{ vtiger_db_name }} -u{{vtiger_db_user}} -p{{vtiger_db_password}} < maestrano/app/db/1_add_mno_uid_field.sql"
#   args:
#     chdir: "{{ vtiger_root_path }}"

# - name: vTiger | Set log files permissions
#   file:
#     path: /var/log/apache2
#     mode: 0755
#     owner: www-data
#     group: www-data
#     state: directory
#     recurse: yes
#   tags:
#     - configuration

# - name: vTiger | Import Connec! data
#   shell: "(nohup php initialize.php 1>/var/log/apache2/vtigercrm_initialize.log 2>&1) &"
#   args:
#     chdir: "{{ vtiger_root_path }}/maestrano/scripts"
#   sudo_user: www-data
#   tags:
#     - configuration
